module.exports = function(grunt) {

  // project configuration
  grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),

    watch: {
      scripts: {
        files: [
          'site/resources/**/*.scss',
          'site/js/*.js',
          '!site/js/app*.js',
          'site/js/vendor/*.js'
        ],
        tasks: ['dev'],
        options: {
          interrupt: true,
        }
      }
    },

    compass: {
      dist: {
        options: {
          config: 'config.rb',
          boring: true,
          trace: true
        }
      }
    },

    concat: {
      options: {
        separator: ';',
      },
      js: {
        src: ['site/js/jquery.js','site/js/vendor/*.js','site/js/bronycon.js'],
        dest: 'site/js/app.js',
      }
    },

    uglify: {
      options: {
        mangle: {toplevel: true},
        squeeze: {dead_code: false},
        codegen: {quote_keys: true}
      },
      default: {
        src: 'site/js/app.js',
        dest: 'site/js/app.min.js'
      }
    },

    cssmin: {
      options: {
        keepSpecialComments: 0
      },
      minify: {
        expand: true,
        cwd: 'site/css/',
        src: ['*.css', '!*.min.css'],
        dest: 'site/css/',
        ext: '.min.css'
      }
    },

    cachebuster: {
      options: {
        basedir: 'site/',
        format: 'php',
        banner:
          '/**\n' +
          ' * GENERATED FILE, DO NOT EDIT. This file is simply a collection of generated hashes for static assets in \n' +
          ' * the project. It is generated by grunt, see Gruntfile.js for details.\n' +
          ' */',
        complete: function(hashes) {
          return {
            md5: hashes
          };
        }
      },
      production: {
        src: [ 'site/css/app.min.css', 'site/js/app.min.js' ],
        dest: 'site/cachebuster.php'
      },
      dev: {
        src: [ 'site/css/app.css', 'site/js/app.js' ],
        dest: 'site/cachebuster.php'
      }
    }
    
  });

  // load all the things
  grunt.loadNpmTasks('grunt-contrib-watch');
  grunt.loadNpmTasks('grunt-contrib-compass');
  grunt.loadNpmTasks('grunt-contrib-concat');
  grunt.loadNpmTasks('grunt-contrib-uglify');
  grunt.loadNpmTasks('grunt-contrib-cssmin');
  grunt.loadNpmTasks('grunt-cachebuster');

  // tasks
  grunt.registerTask('default', ['compass','concat','uglify','cssmin','cachebuster:production']);
  grunt.registerTask('dev', ['compass','concat','cachebuster:dev']);
};